server:
  port: 8081

spring:
  application:
    name: customer-service
  profiles:
    active: local
  
  h2:
    console:
      enabled: true
      path: /h2-console
  
  r2dbc:
    url: r2dbc:h2:mem:///customer_db
    username: sa
    password: password

management:
  endpoints:
    web:
      exposure:
        include: health,info
