server:
  port: 8082

spring:
  web:
    locale: es
  application:
    name: account-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:development}
  kafka:
    properties:
      sasl:
        mechanism: PLAIN
        jaas:
          config: org.apache.kafka.common.security.plain.PlainLoginModule required username= ${KAFKA_USER:optimus-user} password=${KAFKA_PASSWORD:optimus-pass};
      bootstrap:
        servers: ${KAFKA_BOOTSTRAP_SERVERS:pkc-56d1g.eastus.azure.confluent.cloud:9092}
      security:
        protocol: ${KAFKA_SECURITY_PROTOCOL:SASL_SSL}
      session:
        timeout:
          ms: 45000
      request:
        timeout:
          ms: 2000
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
logging:
  level:
    org:
      apache:
        kafka: OFF
  transactional:
    sendLog: true
    kafka:
      topic:
        name: ${KAFKA_TOPIC:}
    tracer:
      exclusion:
        uri: actuator,swagger,api-docs,csrf,favicon  
    obfuscation:
      fields: ${MY_FIELDS_TO_OFUSCATE:(id)|(phone)|(lastName)}
      enabled: false
      character: '*****************'
      obfuscation-type: REQUEST
    handle-error:
      status-code: 404
  auditor:
    mode: 'CONSOLE'
    obfuscation:
      fields: ${MY_FIELDS_TO_OFUSCATE:(id)|(phone)|(lastName)}
      enable: false
control:
  errors:
    trace: false